# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 24.1.1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    -   id: black
        language_version: python3 # Should be a command that runs python3.6+
-   repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    -   id: jupyter-notebook-cleanup
        args:
        -   --remove-kernel-metadata
        -   --pin-patterns
        -   "[keep_output]"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=5120"]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: .*/tests/.*|poetry.lock
